-- =====================================================================
-- OPERATOR FILE -- migration 0021 (live_source_ingestion)
--
-- GENERATED BY db/tools/build-operator-sql.mjs. DO NOT EDIT BY HAND.
-- Edit db/migrations/0021_live_source_ingestion.up.sql and regenerate; CI fails if the
-- two drift apart.
--
-- HOW TO RUN IT
--
--   Supabase Dashboard -> SQL Editor -> paste this ENTIRE file -> Run.
--   Or: psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f <this file>
--
--   There is nothing to paste INTO it, nothing to substitute, and no section
--   left out. The whole migration is below.
--
-- WHAT IT GUARANTEES
--
--   It is ONE statement. A DO block is a single statement and therefore a
--   single transaction, whatever the client does with the script around it --
--   which matters because the Supabase SQL Editor does not keep one session
--   across the statements of a script, so an explicit begin/commit would NOT
--   wrap a multi-statement version of this file.
--
--   Either every object below exists AND the ledger row is recorded, or
--   neither is. There is no path that produces one without the other.
--
--   There is no dynamic SQL: the migration's statements are inlined verbatim
--   as PL/pgSQL statements, so the payload here is byte-identical to the
--   canonical migration.
--
-- WHAT IT REFUSES
--
--   Any line containing ABORT: means NOTHING WAS COMMITTED. The block refuses
--   if 0018 or 0020 is missing, if 0021 is already recorded, if the recorded
--   0020 checksum is not the expected one, or if the Microsoft identity guard
--   from 0020 is not present.
--
-- CHECKSUMS (whitespace-normalised per line, sha256 -- the rule db/migrate.mjs
-- uses, so a file applied this way verifies clean afterwards)
--
--   0021  fd15cdc30a526e9575fe9c0644d8055e4346290ea8d7596048f78b9e7afc53b7
--   0020  55514d77a1e92019598127d733df47f1895eb6166c5ddf003df10a1ebb968832   (read, never modified)
-- =====================================================================

do $operator_0021$
begin
    -- ------------------------------------------------------------ preconditions
    if to_regclass('public.schema_migrations') is null then
        raise exception 'ABORT: there is no schema_migrations ledger. This database has never been migrated by db/migrate.mjs.';
    end if;

    if exists (select 1 from public.schema_migrations where version = '0021') then
        raise exception 'ABORT: migration 0021 is already recorded. Nothing to do.';
    end if;

    if not exists (select 1 from public.schema_migrations where version = '0018') then
        raise exception 'ABORT: migration 0018 is not present. This database is older than 0021 expects.';
    end if;

    if not exists (select 1 from public.schema_migrations where version = '0020') then
        raise exception 'ABORT: migration 0020 is not present. Apply it first; the hosted order is 0018, 0020, 0021.';
    end if;

    -- 0020 IS READ HERE AND NEVER WRITTEN. 0021 touches no auth object, and
    -- these two checks are the cheapest way to prove that afterwards: they
    -- establish the guard was intact BEFORE, so the identical checks at the end
    -- mean something.
    if not exists (
        select 1 from public.schema_migrations
        where version = '0020' and checksum = '55514d77a1e92019598127d733df47f1895eb6166c5ddf003df10a1ebb968832'
    ) then
        raise exception 'ABORT: the recorded checksum for migration 0020 is not the expected value. Do not proceed; investigate the ledger first.';
    end if;

    if to_regproc('public.auth_guard_microsoft_identity') is null then
        raise exception 'ABORT: auth_guard_microsoft_identity is missing. Migration 0020 is recorded but its objects are not there.';
    end if;

-- >>>>>>>>>>>>>>>>>>>>>> CANONICAL PAYLOAD BEGINS <<<<<<<<<<<<<<<<<<<<<<
-- Verbatim from db/migrations/0021_live_source_ingestion.up.sql, minus its own
-- begin;/commit; lines. Nothing else is changed. Diff it if you like.

-- ---------------------------------------------------------------- evidence

alter table evidence
    add column source_document_id    text,
    add column document_revision     text,
    add column connector_id          text,
    add column connector_version     text,
    add column first_seen_at         timestamptz not null default now(),
    add column last_seen_at          timestamptz not null default now(),
    add column classification_status text not null default 'unclassified',
    add column review_status         text not null default 'unreviewed',
    add column superseded_at         timestamptz;

comment on column evidence.superseded_at is
    'When this version stopped being current. Set BEFORE the replacement row exists, which is what lets a correction be written without ever having two current rows or a forward reference to a row that has not been inserted yet.';

comment on column evidence.source_document_id is
    'Stable identifier for the document AT THE SOURCE: an SEC accession number, a feed guid, a canonical newsroom path. Distinct from content_hash, which identifies the bytes.';
comment on column evidence.document_revision is
    'Source-declared revision marker where one exists (ETag, amendment suffix). Advisory only; supersession is decided by content_hash.';
comment on column evidence.first_seen_at is
    'When this document was FIRST observed. Never moves.';
comment on column evidence.last_seen_at is
    'When this document was most recently observed to still exist. Moves on every run that sees it again, without touching published_at.';

alter table evidence
    add constraint evidence_classification_status_check
        check (classification_status in (
            'unclassified',        -- ingested, not yet evaluated
            'not_relevant',        -- evaluated, carries no Haskell-relevant signal
            'candidate_signal',    -- evaluated, may support a signal
            'supporting_evidence'  -- linked to at least one signal
        )),
    add constraint evidence_review_status_check
        check (review_status in (
            'unreviewed',
            'analyst_confirmed',
            'analyst_rejected',
            'manual_review_required'
        ));

-- ONE CURRENT VERSION PER DOCUMENT. Superseded rows are excluded, so history
-- accumulates without ever producing two live rows for the same document.
-- Keyed on `superseded_at`, NOT on `superseded_by_evidence_id`.
--
-- The pointer is a foreign key, so it cannot be set until the replacement row
-- exists — and the replacement row cannot be inserted while the old one still
-- holds the key. Marking the old version retired first breaks that deadlock:
--   1. update old  set superseded_at = now()      -- key is now free
--   2. insert new                                  -- takes the key
--   3. update old  set superseded_by = new.id      -- links the history
-- At no point are there two current rows, and at no point is there a forward
-- reference to a row that does not exist.
create unique index evidence_current_document_uidx
    on evidence (source_id, source_document_id)
    where source_document_id is not null and superseded_at is null;

-- A retired row must say what replaced it, and a live row must not claim a
-- replacement. Without this the two columns could disagree silently.
alter table evidence
    add constraint evidence_supersession_is_consistent
        check (superseded_by_evidence_id is null or superseded_at is not null);

-- The re-observation path reads by document id constantly; without this every
-- run table-scans evidence once per document discovered.
create index evidence_document_lookup_idx
    on evidence (source_id, source_document_id)
    where source_document_id is not null;

create index evidence_last_seen_idx on evidence (last_seen_at desc);

-- WHY THERE IS NO `published_at <> retrieved_at` CONSTRAINT.
--
-- An earlier draft of this migration forbade the two from being equal, on the
-- theory that a careless assignment of the retrieval time into the publication
-- field would otherwise be invisible. That rule was wrong, and wrong in the
-- expensive direction: the two columns record different FACTS, and those facts
-- can coincide. A feed polled seconds after publication, a source that states
-- times only to the minute, and historical metadata normalised to the same
-- precision as retrieval all produce legitimate rows where the values match.
-- A constraint that rejects them destroys real data to catch a coding error.
--
-- The coding error is prevented where it actually occurs: the pipeline reads
-- `published_at` only from what the SOURCE stated, and leaves it null when the
-- source states nothing. `retrieved_at` is already NOT NULL, so a retrieved
-- document always records when it was fetched. Equality is then a coincidence
-- the database has no business adjudicating.

-- ----------------------------------------------------------------- signals

-- `cluster_key` existed as a column with nothing enforcing it. One cluster per
-- organization is what stops the same announcement becoming three signals.
create unique index signals_organization_cluster_uidx
    on signals (organization_id, cluster_key)
    where cluster_key is not null;

-- ----------------------------------------------------------- opportunities

-- AN UNSCORED OPPORTUNITY IS NULL, NOT ZERO.
--
-- These columns were NOT NULL, which forced anything creating an opportunity to
-- supply a number. A signal-derived opportunity has not been scored yet — the
-- scoring configuration is versioned and one axis is still gated on the D14-L
-- licence review — and writing a placeholder would put a fabricated score in
-- the same column an analyst's real one lives in. Existing rows keep their
-- values; only the requirement is lifted.
alter table opportunities
    alter column haskell_fit           drop not null,
    alter column project_maturity      drop not null,
    alter column potential_scope       drop not null,
    alter column timing_momentum       drop not null,
    alter column raw_score             drop not null,
    alter column confidence_multiplier drop not null,
    alter column final_score           drop not null,
    alter column why_it_matters        drop not null;

alter table opportunities
    add column opportunity_key text,
    add column derived_by      text,
    add column derived_at      timestamptz;

comment on column opportunities.opportunity_key is
    'Stable derivation key. An opportunity re-derived from the same signals updates in place instead of appearing twice.';
comment on column opportunities.derived_by is
    'Connector or pipeline version that derived this. Null for an analyst-created record.';

create unique index opportunities_organization_key_uidx
    on opportunities (organization_id, opportunity_key)
    where opportunity_key is not null;

-- -------------------------------------------------------------- source_runs

-- OVERLAPPING RUNS, PREVENTED BY THE DATABASE.
--
-- A schedule that fires twice, or a manual run racing the schedule, must not
-- produce two concurrent collections against one source. The application can
-- check first and still lose the race; a partial unique index cannot.
create unique index source_runs_single_active_uidx
    on source_runs (source_id)
    where run_status = 'running';

-- ------------------------------------------------------------------ sources

-- Two honest connector states the vocabulary could not previously express.
-- `unsupported` meant "we will never support this"; neither of these does.
alter table sources drop constraint sources_health_status_check;
alter table sources
    add constraint sources_health_status_check
        check (health_status in (
            'healthy',
            'degraded',
            'action_required',
            'disabled',
            'unsupported',
            'manual_review_required',  -- reachable, but no compliant automated path
            'source_unavailable'       -- retrieval failed; NOT a statement about relevance
        ));

alter table sources
    add column connector_id       text,
    add column connector_config   jsonb not null default '{}'::jsonb,
    add column last_success_at    timestamptz;

comment on column sources.connector_config is
    'Retrieval strategy for this source, as data rather than code: candidate feed URLs, page patterns, filing-type filters. Editable during an operator backfill without a deploy.';
comment on column sources.last_success_at is
    'Last run that actually completed retrieval. What the interface means by "as of".';

-- --------------------------------------------- conditional-request validators

-- SEC fair access is a rate limit AND not re-fetching what has not changed.
-- Storing the validators is the only way to send If-None-Match / If-Modified-Since.
create table source_document_cache (
    id             uuid primary key default gen_random_uuid(),
    source_id      text not null references sources (id) on delete cascade,
    request_url    text not null,
    etag           text,
    last_modified  text,
    content_hash   char(64),
    status         integer,
    fetched_at     timestamptz not null default now(),
    hit_count      integer not null default 0,
    created_at     timestamptz not null default now(),
    unique (source_id, request_url),
    constraint source_document_cache_has_validator
        check (etag is not null or last_modified is not null or content_hash is not null)
);

comment on table source_document_cache is
    'ETag / Last-Modified validators per request URL. Never stores response bodies — only what is needed to ask "has this changed?".';

create index source_document_cache_fetched_idx on source_document_cache (source_id, fetched_at desc);

-- RLS, on the same terms as every other table (0015). This holds retrieval
-- metadata for public documents, but "not secret" is not a reason to expose a
-- table to anon: the default is deny and this one is server-side only.
alter table source_document_cache enable row level security;
alter table source_document_cache force row level security;

-- No policy is created deliberately: with RLS enabled and no policy, every
-- role except the bypassing service_role reads nothing. The ingestion path is
-- the only legitimate reader and it runs as service_role.

-- >>>>>>>>>>>>>>>>>>>>>>> CANONICAL PAYLOAD ENDS <<<<<<<<<<<<<<<<<<<<<<<

    -- ------------------------------------------------------------- ledger row
    -- Inside the same transaction as the payload. That is the whole design:
    -- objects without a ledger row, or a ledger row without objects, are both
    -- unreachable states.
    insert into public.schema_migrations (version, name, checksum, stamped)
    values ('0021', 'live_source_ingestion', 'fd15cdc30a526e9575fe9c0644d8055e4346290ea8d7596048f78b9e7afc53b7', false);

    -- ----------------------------------------------------------- postconditions
    -- Asserted, not assumed. A silent partial application is exactly what this
    -- file exists to make impossible, so it proves the result before returning.
    if to_regclass('public.source_document_cache') is null then
        raise exception 'ABORT: source_document_cache was not created.';
    end if;
    if to_regclass('public.evidence_current_document_uidx') is null then
        raise exception 'ABORT: evidence_current_document_uidx was not created.';
    end if;
    if to_regclass('public.evidence_document_lookup_idx') is null then
        raise exception 'ABORT: evidence_document_lookup_idx was not created.';
    end if;
    if to_regclass('public.evidence_last_seen_idx') is null then
        raise exception 'ABORT: evidence_last_seen_idx was not created.';
    end if;
    if to_regclass('public.signals_organization_cluster_uidx') is null then
        raise exception 'ABORT: signals_organization_cluster_uidx was not created.';
    end if;
    if to_regclass('public.opportunities_organization_key_uidx') is null then
        raise exception 'ABORT: opportunities_organization_key_uidx was not created.';
    end if;
    if to_regclass('public.source_runs_single_active_uidx') is null then
        raise exception 'ABORT: source_runs_single_active_uidx was not created.';
    end if;

    if (select count(*) from information_schema.columns
        where table_schema = 'public' and table_name = 'evidence'
          and column_name in ('source_document_id','document_revision','connector_id',
                              'connector_version','first_seen_at','last_seen_at',
                              'classification_status','review_status','superseded_at')) <> 9 then
        raise exception 'ABORT: the evidence columns are not all present.';
    end if;

    if (select count(*) from information_schema.columns
        where table_schema = 'public' and table_name = 'opportunities'
          and column_name in ('opportunity_key','derived_by','derived_at')) <> 3 then
        raise exception 'ABORT: the opportunities columns are not all present.';
    end if;

    if (select count(*) from information_schema.columns
        where table_schema = 'public' and table_name = 'sources'
          and column_name in ('connector_id','connector_config','last_success_at')) <> 3 then
        raise exception 'ABORT: the sources columns are not all present.';
    end if;

    -- The scoring columns must now admit null, or an unscored opportunity is
    -- impossible and the collector is forced to invent a number.
    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'opportunities'
          and column_name in ('haskell_fit','project_maturity','potential_scope',
                              'timing_momentum','raw_score','confidence_multiplier',
                              'final_score','why_it_matters')
          and is_nullable = 'NO'
    ) then
        raise exception 'ABORT: an opportunities scoring column is still NOT NULL.';
    end if;

    if (select count(*) from public.schema_migrations where version = '0021') <> 1 then
        raise exception 'ABORT: 0021 is not recorded exactly once.';
    end if;

    -- 0020, unchanged, checked again now that 0021 has run.
    if not exists (
        select 1 from public.schema_migrations
        where version = '0020' and checksum = '55514d77a1e92019598127d733df47f1895eb6166c5ddf003df10a1ebb968832'
    ) then
        raise exception 'ABORT: the 0020 ledger row changed while 0021 was applying.';
    end if;
    if to_regproc('public.auth_guard_microsoft_identity') is null then
        raise exception 'ABORT: auth_guard_microsoft_identity disappeared while 0021 was applying.';
    end if;

    raise notice 'Migration 0021 applied and recorded. 0020 and the Microsoft identity guard are intact.';
end
$operator_0021$;
