/**
 * Emit `dist/_headers` with a Content-Security-Policy naming THIS deployment's
 * Supabase project.
 *
 * The policy has to be generated rather than written into `netlify.toml`,
 * because the one origin the browser is allowed to talk to is the project URL,
 * and that differs between the development project, a preview and production.
 * A static policy could only be permissive enough to cover all three, which is
 * the opposite of what a narrow allowlist is for.
 *
 * With no `VITE_SUPABASE_URL` configured the policy falls back to
 * `connect-src 'self'` — same-origin Netlify Functions only, no Supabase, no
 * anything else. That is the correct posture for a build that has not been
 * pointed at a project: fail closed, not open.
 */
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const APP = dirname(dirname(fileURLToPath(import.meta.url)))
const DIST = join(APP, 'dist')

function supabaseOrigins(raw) {
  if (!raw) return []
  let url
  try {
    url = new URL(raw)
  } catch {
    throw new Error(`VITE_SUPABASE_URL is not a valid URL: ${raw}`)
  }
  if (url.protocol !== 'https:') {
    throw new Error(`VITE_SUPABASE_URL must be https, got ${url.protocol}`)
  }
  // HTTPS only. The realtime WebSocket origin is deliberately NOT granted: this
  // application uses Supabase REST, Auth and Storage, and does not open a
  // realtime channel anywhere. Reserving `wss://` for a feature that might
  // arrive later widens the policy today in exchange for nothing, and a CSP that
  // permits more than the app uses stops describing the app.
  //
  // If realtime is ever adopted, add it here in the same change that adds the
  // first `.channel()` call — so the grant and its justification land together.
  return [`https://${url.host}`]
}

/**
 * `index.html` carries one inline script: the pre-paint theme applier, which has
 * to run before first paint or a chosen theme flashes the other one.
 *
 * It is admitted by SHA-256 hash rather than by `'unsafe-inline'`. A hash names
 * exactly that script; `'unsafe-inline'` names every inline script anyone ever
 * adds, including one injected through a rendering bug. Hashing here also means
 * that if the script is edited and the hash is not regenerated, the script stops
 * running loudly instead of the policy silently going slack.
 */
function inlineScriptHashes() {
  let html
  try {
    html = readFileSync(join(DIST, 'index.html'), 'utf8')
  } catch {
    return []
  }
  const hashes = []
  const pattern = /<script(?![^>]*\ssrc=)[^>]*>([\s\S]*?)<\/script>/g
  let match
  while ((match = pattern.exec(html)) !== null) {
    const body = match[1]
    if (!body) continue
    hashes.push(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`)
  }
  return hashes
}

const origins = supabaseOrigins(process.env.VITE_SUPABASE_URL)
const scriptHashes = inlineScriptHashes()

// 'self' covers the same-origin Netlify Functions under /api/*. Everything else
// is enumerated. No wildcards, no scheme-only sources.
const connectSrc = ["'self'", ...origins].join(' ')

const policy = [
  "default-src 'self'",
  ["script-src 'self'", ...scriptHashes].join(' '),
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src ${connectSrc}`,
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
].join('; ')

const body = `# Generated by scripts/generate-headers.mjs at build time. Do not edit.
/*
  Content-Security-Policy: ${policy}
`

mkdirSync(DIST, { recursive: true })
writeFileSync(join(DIST, '_headers'), body, 'utf8')

// A guard, not decoration: `wss:` must not reappear without a deliberate edit
// above, and a generator is exactly the place a stray scheme slips back in.
if (policy.includes('wss:')) {
  throw new Error(
    'The generated CSP grants a WebSocket origin, but this application opens no ' +
      'realtime channel. Remove it, or add it together with the code that needs it.',
  )
}

console.log(
  origins.length
    ? `_headers written; connect-src permits ${origins.join(' and ')}`
    : "_headers written; VITE_SUPABASE_URL is unset so connect-src is 'self' only",
)
console.log(
  scriptHashes.length
    ? `script-src admits ${scriptHashes.length} inline script(s) by hash, not by 'unsafe-inline'`
    : "script-src admits no inline script",
)
